# SPDX-FileCopyrightText: 2025 Contributors to the Media eXchange Layer project.
# SPDX-License-Identifier: Apache-2.0

FROM debian:trixie-slim

WORKDIR /app

RUN apt update && apt-get -y install\
        procps \
        patchelf && rm -rf /var/lib/apt/lists/*

##### EXTRA - START #####
# Install GStreamer and plugins for SRT support. 
RUN apt-get update && apt-get -y install \
        libglib2.0-0 \
        libgstreamer1.0-0 \
        libgstreamer-plugins-base1.0-0 \
        gstreamer1.0-plugins-good \
        gstreamer1.0-plugins-bad \
        gstreamer1.0-plugins-ugly \
        # testing
        gstreamer1.0-tools \
        gstreamer1.0-libav \
        libssl-dev && rm -rf /var/lib/apt/lists/*
##### EXTRA - END #####

COPY build/Linux-Clang-Release/lib/*.so* /app/
COPY build/Linux-Clang-Release/lib/internal/*.so* /app/
COPY build/Linux-Clang-Release/tools/mxl-info/mxl-info /app/

RUN patchelf --set-rpath /app mxl-info

##### EXTRA - START #####
# Copy the mxl-gst-sink plugin to the container.
COPY build/Linux-Clang-Release/tools/mxl-gst/mxl-gst-sink /app/
RUN patchelf --set-rpath /app mxl-gst-sink
##### EXTRA - END #####

# Check ./SRT_OUT_README.md for instructions on how to use this image.

CMD ["sh", "-c", "while true; do /app/mxl-info -d /domain -l || true; sleep 2; done"]